spring.application.name=Saber-Pro_Parcial
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.uri=mongodb+srv://jcgg1204_db_user:juan2006@clase.0yzmjjz.mongodb.net/saberpro?retryWrites=true&w=majority
spring.data.mongodb.database=saberpro
server.port=8107